### ISSUE TITLE
Ready for Deploymeny

### ISSUE THREAD

**Issue by akshaybahadur21** [darxa/darxa-google-ai#1]
@darxa @SKKSaikia - I think you have done great work till.
I have 1 question, Is this product ready for deployment?

**Comment by florist-notes** [comment]
@akshaybahadur21 it is not ready for a full-fledged deployment. However, we built a basic architecture to transfer data. We are working on Deep Learning algorithms and also hardware. It needs more work for deployment.

**Comment by akshaybahadur21** [comment]
@SKKSaikia - Your project is quite good and useful.
For starters, I think if you could explain an end to end video of how the project works, or it will work in the field.
I think that would be really helpful in explaining the general audience.
Let me know if you want to add some points to this?

**Comment by florist-notes** [comment]
@akshaybahadur21 We are excited to work on it. Sure, working on an end-to-end video, will release soon. We need your mentorship in making this more robust and we need your input.

**Comment by akshaybahadur21** [comment]
@SKKSaikia - Definitely.
I can see that you have some Todo tasks left.
Let me know which you want to go ahead with next so that we can establish a pipeline for the same.

**Comment by florist-notes** [comment]
Sure, I emailed you.
